---
- name: yay
  tags: [yay, aur]
  block:
    - name: Set up the AUR builder and install yay on Arch Linux
      when: ansible_facts['distribution'] == 'Archlinux'
      block:
        - name: Install the build toolchain makepkg needs
          become: true
          community.general.pacman:
            name: base-devel
            state: present

        - name: Create the `aur_builder` user
          become: true
          ansible.builtin.user:
            name: aur_builder
            create_home: true
            group: wheel

        - name: Allow the `aur_builder` user to run `sudo pacman` without a password
          become: true
          ansible.builtin.lineinfile:
            path: /etc/sudoers.d/11-install-aur_builder
            line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
            create: true
            mode: "0440"
            validate: "visudo -cf %s"

        - name: Install yay-bin
          kewlfft.aur.aur:
            use: makepkg
            name: yay-bin
            state: present
          become: true
          become_user: aur_builder
