---
- name: Configure local machine
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Dynamically load host-specific variables matching system hostname
      ansible.builtin.include_vars:
        file: "inventories/local/host_vars/{{ ansible_facts['hostname'] }}.yml"

  roles:
    - role: system_user
      tags: [system_user, base]

    - role: nvim
      tags: [nvim, base]

    - role: tmux
      tags: [tmux, base]

    - role: fonts
      tags: [fonts, gui]

    - role: alacritty
      tags: [alacritty, gui]

    - role: niri
      tags: [niri, gui]
      when: niri | default(false) | bool
