---
- name: Configure local machine
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Load host vars matching system hostname
      ansible.builtin.include_vars:
        file: "inventories/local/host_vars/{{ ansible_facts['hostname'] }}.yml"
      tags: [always]

  tasks:
    - name: Run the roles selected for this host
      ansible.builtin.include_role:
        name: "{{ machine_profile }}"
      tags: [always]