---
- name: Configure local machine
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Load host vars matching system hostname
      ansible.builtin.include_vars:
        file: "inventories/local/host_vars/{{ ansible_facts['hostname'] }}.yml"
      tags: [always]

  tasks:
    - name: Run roles defined in host_vars
      ansible.builtin.include_role:
        name: "{{ role_item }}"
        apply:
          tags: ["{{ role_item }}"]
      loop: "{{ enabled_roles }}"
      loop_control:
        loop_var: role_item
      tags: [always]
