---
- name: Machine setup
  hosts: workstations

  roles:
    - role: system_user
      tags: [system_user, base]

    - role: fonts
      tags: [fonts, gui]

    - role: alacritty
      tags: [alacritty, gui]
