---
- name: Install
  become: true
  ansible.builtin.package:
    name: tmux
    state: present

- name: Ensure config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/tmux"
    state: directory
    mode: '0755'

- name: Symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/tmux.conf"
    state: link
    force: true
