---
- name: Install
  become: true
  ansible.builtin.package:
    name: waybar
    state: present

- name: Symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/waybar"
    dest: "{{ ansible_facts['user_dir'] }}/.config/waybar"
    state: link
    force: true
