---
- name: Install on arch
  become: true
  community.general.pacman:
    name: xdg-user-dirs
    state: present
  when: ansible_facts['pkg_mgr'] == 'pacman'

- name: Update XDG user directories for username
  ansible.builtin.command: xdg-user-dirs-update
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.config/user-dirs.dirs"
