---
ansible_become_pass: "{{ vault_sudo_password }}"

profiles:
  base:
    - xdg_user_dirs
    - cli_tools
    - git
    - zsh
    - yay
  desktop:
    - tuigreet
    - niri
    - noctalia
    - fonts
    - gtk
  dev:
    - aur_cli_tools
    - nvim
    - tmux
