set -g default-terminal "tmux-256color"
set -g prefix C-SPACE

set -g base-index 1
set -g renumber-windows on   

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-left "#S"
set -g status-right ""


### VIM ###
set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection


### PANES ###
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r "<" swap-window -d -t -1
bind-key -r ">" swap-window -d -t +1

bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"

bind-key c new-window -c "#{pane_current_path}"


### WINDOWS ###
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
bind-key -n M-0 select-window -t 10


### SESSIONS ###
bind-key Tab choose-tree -s


### PLUGINS ###
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

### PLUGIN CONFIG ###
set -g @vim_navigator_mapping_left "M-h"
set -g @vim_navigator_mapping_right "M-l"
set -g @vim_navigator_mapping_up "M-k"
set -g @vim_navigator_mapping_down "M-j"

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"
run '~/.config/tmux/plugins/tpm/tpm'
