---
- name: Install on arch
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - base-devel
    - cmake
    - fd
    - fzf
    - npm
    - ripgrep
    - rust
    - unzip
    - wl-clipboard
    - yazi
    - zoxide
  when: ansible_facts.pkg_mgr == 'pacman'
