---
- name: cli_tools
  tags: [cli_tools]
  block:
    - name: Install on arch
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - cmake
        - fd
        - fzf
        - npm
        - ripgrep
        - rust
        - unzip
        - wl-clipboard
        - yazi
        - zoxide
      when: ansible_facts.pkg_mgr == 'pacman'

    - name: Install AUR cli tools on Arch Linux
      when: ansible_facts['distribution'] == 'Archlinux'
      block:
        - name: Install
          kewlfft.aur.aur:
            use: yay
            name: "{{ item }}"
            state: present
          become: true
          become_user: aur_builder
          loop:
            - sesh-bin