---
- name: fonts
  tags: [fonts]
  block:
    - name: Install on arch
      become: true
      community.general.pacman:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - inter-font
        - adobe-source-serif-fonts
        - ttf-jetbrains-mono-nerd
      when: ansible_facts['pkg_mgr'] == 'pacman'

    - name: Ensure target font directory exists
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.local/share/fonts/FiraCode"
        state: directory
        mode: '0755'

    - name: Download and extract FiraCode Nerd Font
      ansible.builtin.unarchive:
        src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.5.1/FiraCode.zip"
        dest: "{{ ansible_facts['user_dir'] }}/.local/share/fonts/FiraCode"
        remote_src: yes
        creates: "{{ ansible_facts.user_dir }}/.local/share/fonts/FiraCode/FiraCodeNerdFont-Regular.ttf"
      register: font_installed
      when: ansible_facts['pkg_mgr'] != 'pacman'

    - name: Refresh font cache
      ansible.builtin.command: fc-cache -fv
      when: font_installed.changed
